title: "CallTech Blog"
description: "AI-powered Telephony, Call Center Analytics & Speech Tech Insights"
url: "https://calltechapp.github.io"
baseurl: ""
email: info@calltech.app
twitter_username: calltechapp
github_username: calltechapp
minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages
  - en
  - tr

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "Calltech AI"
  avatar : "/assets/images/avatar.jpg"
  bio    : "Tech notes from the team behind Calltech's AI voice analytics platform."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://calltech.app"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/calltechapp"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/calltechapp"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/calltechapp"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


collections:
  posts:
    output: true
    permalink: /en/:categories/:year/:month/:day/:title/
defaults:
  - scope:
      path: "en"
      type: "posts"
    values:
      layout: "single"
      lang: "en"


collections:
  posts:
    output: true
    permalink: /tr/:categories/:year/:month/:day/:title/
defaults:
  - scope:
      path: "tr"
      type: "posts"
    values:
      layout: "single"
      lang: "tr"

